from conans import ConanFile, CMake, tools
import os
import glob


class LlvmConan(ConanFile):
    name = "llvm"
    version = "8.0.0"
    license = "MIT"
    author = "<Put your name here> <And your email here>"
    url = "https://github.com/woidpointer/conan-llvm"
    description = "<Description of Llvm here>"
    topics = ("llvm", "clang")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def source(self):
        cmd = []
        cmd.append("git clone")
        cmd.append("https://github.com/llvm/llvm-project.git -b")
        cmd.append("llvmorg-{} --depth 1".format(self.version))

        self.run(" ".join(cmd))

    def build(self):
        
        if self.settings.compiler == 'Visual Studio':
            cmake = CMake(self, toolset="v141")            
        else:
            cmake = CMake(self)                       
        
        cmake.definitions["LLVM_ENABLE_PROJECTS"] = "clang"
        source_sub_folder = "{}/llvm-project/llvm".format(self.source_folder)
        cmake.parallel = False
        #print(cmake.command_line)
        cmake.configure(source_folder=source_sub_folder)                      
        cmake.build()
        cmake.install()

    def package(self):
        # copy all artefacts which where generated by LLVM/clang build process
        self.copy(pattern="*", dst="", src="package")

    def package_info(self):
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.bindirs = ["bin"]
        # Add everything what we build into the package:
        # replace leading lib/libWhatever to nothing
        files = [os.path.basename(f) for f in glob.glob("lib/*.lib")]
        # replace fileextenstion to nothing, to get the "raw" library name
        # in order to register this name to conan/cmake
        files = list(map(lambda f: os.path.splitext(f)[0], files))
        self.cpp_info.libs = list(files)



