from conans import ConanFile, CMake, tools
import os
import glob


class LlvmConan(ConanFile):
    name = "llvm"
    version = "8.0.0"
    license = "MIT"
    author = "<Put your name here> <And your email here>"
    url = "https://github.com/woidpointer/conan-llvm"
    description = "<Description of Llvm here>"
    topics = ("llvm", "clang")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def source(self):
        cmd = []
        cmd.append("git clone")
        cmd.append("https://github.com/llvm/llvm-project.git -b")
        cmd.append("llvmorg-{} --depth 1".format(self.version))

        self.run(" ".join(cmd))

    def build(self):
        cmake = CMake(self)
        cmake.definitions["LLVM_ENABLE_PROJECTS"] = "clang"
        cmake.definitions["LLVM_ENABLE_ZLIB"] = "OFF"
        source_sub_folder = "{}/llvm-project/llvm".format(self.source_folder)
        cmake.configure(source_folder=source_sub_folder)
        cmake.parallel = False
        cmake.build()
        cmake.install()

    def package(self):
        # copy all artefacts which where generated by LLVM/clang build process
        self.copy(pattern="*", dst="", src="package")

    def package_info(self):
        self.cpp_info.libdirs = ["lib"]
        self.cpp_info.bindirs = ["bin"]
        # Add everything what we build into the package:
        # replace leading lib/libWhatever to nothing
        files = [f.replace("lib/lib", "") for f in glob.glob("lib/*.a")]
        # replace trailing .a to nothing
        files = [f.replace(".a", "") for f in files]
        self.cpp_info.libs = list(files)



